import type { IntuneCategory } from "~/types/intune";

export const INTUNE_CATEGORIES: IntuneCategory[] = [
  {
    id: "managed-devices",
    name: "Managed Devices",
    description: "All enrolled devices (Windows, iOS, Android, macOS)",
    dangerLevel: "critical",
    listEndpoint: "/deviceManagement/managedDevices",
    deleteEndpoint: "/deviceManagement/managedDevices",
    useBeta: false,
    icon: "devices",
  },
  {
    id: "autopilot-devices",
    name: "Autopilot Devices",
    description: "Windows Autopilot device identities",
    dangerLevel: "critical",
    listEndpoint: "/deviceManagement/windowsAutopilotDeviceIdentities",
    deleteEndpoint: "/deviceManagement/windowsAutopilotDeviceIdentities",
    useBeta: false,
    icon: "autopilot",
  },
  {
    id: "autopilot-profiles",
    name: "Autopilot Deployment Profiles",
    description: "Windows Autopilot deployment profiles",
    dangerLevel: "critical",
    listEndpoint: "/deviceManagement/windowsAutopilotDeploymentProfiles",
    deleteEndpoint: "/deviceManagement/windowsAutopilotDeploymentProfiles",
    useBeta: true,
    icon: "profile",
  },
  {
    id: "mobile-apps",
    name: "Applications",
    description: "Win32, LOB, Store apps, and web apps",
    dangerLevel: "critical",
    listEndpoint: "/deviceAppManagement/mobileApps",
    deleteEndpoint: "/deviceAppManagement/mobileApps",
    useBeta: true,
    icon: "apps",
  },
  {
    id: "app-configurations",
    name: "App Configurations",
    description: "Managed device mobile app configurations",
    dangerLevel: "high",
    listEndpoint: "/deviceAppManagement/mobileAppConfigurations",
    deleteEndpoint: "/deviceAppManagement/mobileAppConfigurations",
    useBeta: true,
    icon: "config",
  },
  {
    id: "app-protection-ios",
    name: "App Protection (iOS)",
    description: "iOS managed app protection policies",
    dangerLevel: "high",
    listEndpoint: "/deviceAppManagement/iosManagedAppProtections",
    deleteEndpoint: "/deviceAppManagement/iosManagedAppProtections",
    useBeta: true,
    icon: "shield",
  },
  {
    id: "app-protection-android",
    name: "App Protection (Android)",
    description: "Android managed app protection policies",
    dangerLevel: "high",
    listEndpoint: "/deviceAppManagement/androidManagedAppProtections",
    deleteEndpoint: "/deviceAppManagement/androidManagedAppProtections",
    useBeta: true,
    icon: "shield",
  },
  {
    id: "app-protection-windows",
    name: "App Protection (Windows)",
    description: "Windows Information Protection policies",
    dangerLevel: "high",
    listEndpoint: "/deviceAppManagement/windowsInformationProtectionPolicies",
    deleteEndpoint: "/deviceAppManagement/windowsInformationProtectionPolicies",
    useBeta: true,
    icon: "shield",
  },
  {
    id: "device-configurations",
    name: "Device Configuration",
    description: "Device configuration policies (templates)",
    dangerLevel: "high",
    listEndpoint: "/deviceManagement/deviceConfigurations",
    deleteEndpoint: "/deviceManagement/deviceConfigurations",
    useBeta: true,
    icon: "settings",
  },
  {
    id: "configuration-policies",
    name: "Settings Catalog",
    description: "Configuration policies (Settings Catalog)",
    dangerLevel: "high",
    listEndpoint: "/deviceManagement/configurationPolicies",
    deleteEndpoint: "/deviceManagement/configurationPolicies",
    useBeta: true,
    icon: "catalog",
  },
  {
    id: "compliance-policies",
    name: "Compliance Policies (Classic)",
    description: "Device compliance policies (template-based)",
    dangerLevel: "high",
    listEndpoint: "/deviceManagement/deviceCompliancePolicies",
    deleteEndpoint: "/deviceManagement/deviceCompliancePolicies",
    useBeta: true,
    icon: "compliance",
  },
  {
    id: "compliance-policies-v2",
    name: "Compliance Policies (Settings Catalog)",
    description: "Device compliance policies (Settings Catalog)",
    dangerLevel: "high",
    listEndpoint: "/deviceManagement/compliancePolicies",
    deleteEndpoint: "/deviceManagement/compliancePolicies",
    useBeta: true,
    icon: "compliance",
  },
  {
    id: "conditional-access",
    name: "Conditional Access",
    description: "Azure AD Conditional Access policies",
    dangerLevel: "critical",
    listEndpoint: "/identity/conditionalAccess/policies",
    deleteEndpoint: "/identity/conditionalAccess/policies",
    useBeta: false,
    icon: "lock",
  },
  {
    id: "powershell-scripts",
    name: "PowerShell Scripts",
    description: "Device management scripts (PowerShell)",
    dangerLevel: "high",
    listEndpoint: "/deviceManagement/deviceManagementScripts",
    deleteEndpoint: "/deviceManagement/deviceManagementScripts",
    useBeta: true,
    icon: "script",
  },
  {
    id: "shell-scripts",
    name: "Shell Scripts (macOS)",
    description: "Device shell scripts for macOS",
    dangerLevel: "high",
    listEndpoint: "/deviceManagement/deviceShellScripts",
    deleteEndpoint: "/deviceManagement/deviceShellScripts",
    useBeta: true,
    icon: "terminal",
  },
  {
    id: "remediation-scripts",
    name: "Remediation Scripts",
    description: "Proactive remediation scripts",
    dangerLevel: "high",
    listEndpoint: "/deviceManagement/deviceHealthScripts",
    deleteEndpoint: "/deviceManagement/deviceHealthScripts",
    useBeta: true,
    icon: "health",
  },
  {
    id: "custom-attribute-scripts",
    name: "Custom Attribute Scripts (macOS)",
    description: "Custom attribute shell scripts for macOS",
    dangerLevel: "high",
    listEndpoint: "/deviceManagement/deviceCustomAttributeShellScripts",
    deleteEndpoint: "/deviceManagement/deviceCustomAttributeShellScripts",
    useBeta: true,
    icon: "attribute",
  },
  {
    id: "enrollment-configurations",
    name: "Enrollment Configurations",
    description: "Device enrollment configurations and restrictions",
    dangerLevel: "high",
    listEndpoint: "/deviceManagement/deviceEnrollmentConfigurations",
    deleteEndpoint: "/deviceManagement/deviceEnrollmentConfigurations",
    useBeta: true,
    icon: "enroll",
    cannotDelete: ["DefaultPlatformRestrictions", "DefaultLimit", "DefaultWindows10EnrollmentCompletionPageConfiguration"],
  },
  {
    id: "group-policy-configurations",
    name: "Administrative Templates (ADMX)",
    description: "Group Policy configurations (ADMX-backed)",
    dangerLevel: "high",
    listEndpoint: "/deviceManagement/groupPolicyConfigurations",
    deleteEndpoint: "/deviceManagement/groupPolicyConfigurations",
    useBeta: true,
    icon: "policy",
  },
  {
    id: "security-baselines",
    name: "Security Baseline Instances",
    description: "Security baseline policy instances",
    dangerLevel: "high",
    listEndpoint: "/deviceManagement/intents",
    deleteEndpoint: "/deviceManagement/intents",
    useBeta: true,
    icon: "baseline",
  },
  {
    id: "assignment-filters",
    name: "Filters",
    description: "Device and app management assignment filters",
    dangerLevel: "medium",
    listEndpoint: "/deviceManagement/assignmentFilters",
    deleteEndpoint: "/deviceManagement/assignmentFilters",
    useBeta: true,
    icon: "filter",
  },
  {
    id: "device-categories",
    name: "Device Categories",
    description: "Device categories for organization",
    dangerLevel: "low",
    listEndpoint: "/deviceManagement/deviceCategories",
    deleteEndpoint: "/deviceManagement/deviceCategories",
    useBeta: true,
    icon: "category",
  },
  {
    id: "scope-tags",
    name: "Scope Tags",
    description: "Role scope tags (custom only)",
    dangerLevel: "medium",
    listEndpoint: "/deviceManagement/roleScopeTags",
    deleteEndpoint: "/deviceManagement/roleScopeTags",
    useBeta: true,
    icon: "tag",
    cannotDelete: ["Default"],
  },
  {
    id: "role-definitions",
    name: "Custom RBAC Roles",
    description: "Custom role definitions (built-in roles cannot be deleted)",
    dangerLevel: "high",
    listEndpoint: "/deviceManagement/roleDefinitions",
    deleteEndpoint: "/deviceManagement/roleDefinitions",
    useBeta: true,
    icon: "role",
  },
  {
    id: "role-assignments",
    name: "Role Assignments",
    description: "RBAC role assignments",
    dangerLevel: "high",
    listEndpoint: "/deviceManagement/roleAssignments",
    deleteEndpoint: "/deviceManagement/roleAssignments",
    useBeta: true,
    icon: "assignment",
  },
  {
    id: "notification-templates",
    name: "Notification Message Templates",
    description: "Compliance notification message templates",
    dangerLevel: "low",
    listEndpoint: "/deviceManagement/notificationMessageTemplates",
    deleteEndpoint: "/deviceManagement/notificationMessageTemplates",
    useBeta: true,
    icon: "notification",
  },
  {
    id: "terms-and-conditions",
    name: "Terms and Conditions",
    description: "Terms and conditions for enrollment",
    dangerLevel: "medium",
    listEndpoint: "/deviceManagement/termsAndConditions",
    deleteEndpoint: "/deviceManagement/termsAndConditions",
    useBeta: true,
    icon: "terms",
  },
];

export const PROTECTED_PATTERNS = [
  /^Default/i,
  /Microsoft managed/i,
  /^All Users$/i,
  /^All Devices$/i,
  /Built-in/i,
];

export function isProtectedObject(displayName: string | undefined): boolean {
  if (!displayName) return false;
  return PROTECTED_PATTERNS.some((pattern) => pattern.test(displayName));
}

export function getCategoryById(id: string): IntuneCategory | undefined {
  return INTUNE_CATEGORIES.find((cat) => cat.id === id);
}

export function getCategoriesByDangerLevel(
  level: IntuneCategory["dangerLevel"]
): IntuneCategory[] {
  return INTUNE_CATEGORIES.filter((cat) => cat.dangerLevel === level);
}
